package com.example.mintosassignment.domain.modals

data class CurrencyRates(
    val aUD: Double,
    val bGN: Double,
    val bRL: Double,
    val cAD: Double,
    val cHF: Double,
    val cNY: Double,
    val cZK: Double,
    val dKK: Double,
    val eUR: Double,
    val gBP: Double,
    val hKD: Double,
    val hUF: Double,
    val iDR: Double,
    val iLS: Double,
    val iSK: Double,
    val jPY: Double,
    val kRW: Double,
    val mXN: Double,
    val mYR: Double,
    val nOK: Double,
    val nZD: Double,
    val pHP: Double,
    val pLN: Double,
    val rON: Double,
    val sEK: Double,
    val sGD: Double,
    val tHB: Double,
    val tRY: Double,
    val uSD: Double,
    val zAR: Double,
    val iNR: Double
)
